name: Build
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: feedbin-web
            context: feedbin-web
            file: Dockerfile
            build-args: FEEDBIN_REPO=https://github.com/AndreasSko/feedbin.git
            tag: latest

          - name: feedbin-web
            context: .
            file: alpine.Dockerfile
            build-args: FEEDBIN_REPO=https://github.com/AndreasSko/feedbin.git
            tag: alpine
    
          - name: feedbin-extract
            file: Dockerfile
            context: feedbin-extract
            tag: latest

          - name: feedbin-image
            file: Dockerfile
            context: feedbin-image
            tag: latest

          - name: feedbin-refresher
            file: Dockerfile
            context: feedbin-refresher
            tag: latest
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker images
        if: github.ref != 'refs/heads/master'
        uses: docker/build-push-action@v2.2.2
        with:
          context: ${{ matrix.image.context }}
          platforms: linux/amd64,linux/arm64
          build-args: ${{ matrix.image.build-args }}
          file: ${{ matrix.image.context }}/${{ matrix.image.file }}

      - name: Build and push Docker images
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2.2.2
        with:
          context: ${{ matrix.image.context }}
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: ${{ matrix.image.build-args }}
          tags: andreassko/${{ matrix.image.name }}:${{ matrix.image.tag }}
          file: ${{ matrix.image.context }}/${{ matrix.image.file }}

  trigger-deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger Deploy workflow on andreassko/infrastructure
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: Terraform
          repo: andreassko/infrastructure
          token: ${{ secrets.WORKFLOW_DISPATCH_GH_TOKEN }}
